apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-ollies-dev-tls
spec:
  secretName: k8s-ollies-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.ollies.dev
  dnsNames:
    - k8s.ollies.dev
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.ollies.dev
